package com.artiks.torcherinoCe.Register;

import com.artiks.torcherinoCe.Items.*;
import com.artiks.torcherinoCe.Tags;
import net.minecraft.item.Item;
import java.util.ArrayList;
import java.util.List;

public final class RegistryItems {
    public static final String mod_id = Tags.MODID + "_";
    public static final List<Item> ITEMS = new ArrayList<>();
    public static final Item time_Wand_lvl1 = new TimeWand(mod_id +"time_wand_lvl1",EnumWands.lvl_1,256);
    public static final Item time_Wand_lvl2 = new TimeWand(mod_id +"time_wand_lvl2",EnumWands.lvl_2,512);
    public static final Item time_Wand_lvl3 = new TimeWand(mod_id +"time_wand_lvl3",EnumWands.lvl_3,1024);
    public static final Item time_Wand_lvl4 = new TimeWand(mod_id +"time_wand_lvl4",EnumWands.lvl_4,2048);
    public static final Item time_Wand_lvl5 = new TimeWand(mod_id +"time_wand_lvl5",EnumWands.lvl_5,4096);
    public static final Item time_Wand_infinite = new TimeWand(mod_id +"time_wand_infinite",EnumWands.infinite,1);
    public static final Item time_storage_lvl1 = new TimeStorage(mod_id +"time_storage_lvl1",EnumStorage.lvl_1);
    public static final Item time_storage_lvl2 = new TimeStorage(mod_id +"time_storage_lvl2",EnumStorage.lvl_2);
    public static final Item time_storage_lvl3 = new TimeStorage(mod_id +"time_storage_lvl3",EnumStorage.lvl_3);
    public static final Item time_storage_lvl4 = new TimeStorage(mod_id +"time_storage_lvl4",EnumStorage.lvl_4);
    public static final Item time_storage_lvl5 = new TimeStorage(mod_id +"time_storage_lvl5",EnumStorage.lvl_5);
    public static final Item time_storage_infinite = new TimeStorage(mod_id +"time_storage_infinite",EnumStorage.infinite);
    public static final Item time_element = new ItemBase(mod_id +"time_element");
    public static final Item time_nugget = new ItemBase(mod_id +"time_nugget");
    public static final Item time_ingot = new ItemBase(mod_id +"time_ingot");
    public static final Item diamond_Clock = new ItemBase(mod_id +"diamondclock");
    public static final Item emerald_Clock = new ItemBase(mod_id +"emeraldclock");
    public static final Item lapis_Clock = new ItemBase(mod_id +"lapisclock");
    public static final Item dragon_Clock = new ItemBase(mod_id +"dragonclock");
    public static final Item redstone_Clock = new ItemBase(mod_id +"redstoneclock");
    public static final Item gold_Clock = new ItemBase(mod_id +"goldclock");
    public static final Item comp_Torch = new ItemBase(mod_id +"compressedtorch");
    public static final Item binding_Element = new ItemBase(mod_id +"bindingelement");
    public static final Item binding_Element2 = new ItemBase(mod_id +"bindingelement2");
    public static final Item binding_Element3 = new ItemBase(mod_id +"bindingelement3");
    public static final Item time_stick = new ItemBase(mod_id +"time_stick");
    public static final Item time_casing = new ItemBase(mod_id +"time_casing");
    public static final Item time_core = new ItemBase(mod_id +"time_core");
    public static final Item time_particle = new ItemBase(mod_id +"time_particle");
    public static final Item time_particle_gold = new ItemBase(mod_id +"time_particle_gold");
    public static final Item time_particle_redstone = new ItemBase(mod_id +"time_particle_redstone");
    public static final Item time_particle_diamond = new ItemBase(mod_id +"time_particle_diamond");
    public static final Item time_particle_emerald = new ItemBase(mod_id +"time_particle_emerald");
    public static final Item time_plate = new ItemBase(mod_id +"time_plate");
    public static final Item time_broken_plate = new ItemBase(mod_id +"time_broken_plate");
    public static final Item time_star = new ItemBase(mod_id +"time_star");
    public static final Item time_energy_star = new ItemBase(mod_id +"time_energy_star");
    public static final Item upgrade_count = new ItemUpgradeCount(mod_id +"upgrade_count");
    public static final Item upgrade_speed = new ItemUpgradeSpeed(mod_id +"upgrade_speed");
    public static final Item gps_marker = new ItemMarker(mod_id +"gps_marker");
    public static final Item upgrade_gps = new ItemBase(mod_id +"upgrade_gps");
    public static final Item upgrade_gps_2 = new ItemBase(mod_id +"upgrade_gps_2");
    public static final Item FortuneModule = new ItemFortuneModule(mod_id + "fortune_module");
    public static final Item EnergyModule = new ItemBase(mod_id + "upgrade_energy");
    public static final Item ExportModule = new ItemExport(mod_id +"upgrade_export");
    public static final Item ImportModule = new ItemImport(mod_id +"upgrade_import");
    public static final Item DragonEgg = new ItemBase(mod_id +"dragon_egg");
    public static final Item raw_time_nugget = new ItemBase(mod_id +"raw_time_nugget");
    public static final Item upgrade_sand = new ItemBase(mod_id + "upgrade_sand");
    public static final Item upgrade_gravel = new ItemBase(mod_id + "upgrade_gravel");

//    public static final Item StackModule = new ItemBase(mod_id +"stack_module");
//    public static final Item InfiniteEngineModule = new ItemBase(mod_id +"infinite_module");
//    public static final Item SmeltingModule = new ItemBase(mod_id +"smelting_module");
}