package com.ariks.torcherino.Register;

import com.ariks.torcherino.Block.Aceleration.BlockAcceleration;
import com.ariks.torcherino.Block.ParticleCollector.ParticleCollectorEnumLevel;
import com.ariks.torcherino.Block.TimeCollector.BlockCollectors;
import com.ariks.torcherino.Block.ParticleCollector.BlockParticleCollector;
import com.ariks.torcherino.Block.TimeManipulator.BlockTimeManipulator;
import com.ariks.torcherino.Block.TimeStorage.BlockTimeStorage;
import com.ariks.torcherino.Block.Torcherino.BlockTorcherino;
import com.ariks.torcherino.Items.*;
import com.ariks.torcherino.Block.Torcherino.TorcherinoEnumLevel;
import com.ariks.torcherino.Torcherino;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import java.util.ArrayList;
import java.util.List;

public final class RegistryArray {
    public static final String modid = Torcherino.MOD_ID + "_";
    public static final List<Item> ITEMS = new ArrayList<>();
    public static final Item Time_Wand_lvl1 = new TimeWand(modid+"time_wand_lvl1",EnumWands.lvl_1,256);
    public static final Item Time_Wand_lvl2 = new TimeWand(modid+"time_wand_lvl2",EnumWands.lvl_2,512);
    public static final Item Time_Wand_lvl3 = new TimeWand(modid+"time_wand_lvl3",EnumWands.lvl_3,1024);
    public static final Item Time_Wand_lvl4 = new TimeWand(modid+"time_wand_lvl4",EnumWands.lvl_4,2048);
    public static final Item Time_Wand_lvl5 = new TimeWand(modid+"time_wand_lvl5",EnumWands.lvl_5,4096);
    public static final Item Time_Wand_infinite = new TimeWand(modid+"time_wand_infinite",EnumWands.infinite,1);
    public static final Item time_storage_lvl1 = new TimeStorage(modid+"time_storage_lvl1",EnumStorage.lvl_1);
    public static final Item time_storage_lvl2 = new TimeStorage(modid+"time_storage_lvl2",EnumStorage.lvl_2);
    public static final Item time_storage_lvl3 = new TimeStorage(modid+"time_storage_lvl3",EnumStorage.lvl_3);
    public static final Item time_storage_lvl4 = new TimeStorage(modid+"time_storage_lvl4",EnumStorage.lvl_4);
    public static final Item time_storage_lvl5 = new TimeStorage(modid+"time_storage_lvl5",EnumStorage.lvl_5);
    public static final Item time_storage_infinite = new TimeStorage(modid+"time_storage_infinite",EnumStorage.infinite);
    public static final Item time_element = new itemBase(modid+"time_element");
    public static final Item time_nugget = new itemBase(modid+"time_nugget");
    public static final Item time_ingot = new itemBase(modid+"time_ingot");
    public static final Item Diamond_Clock = new itemBase(modid+"diamondclock");
    public static final Item Emerald_Clock = new itemBase(modid+"emeraldclock");
    public static final Item Lapis_Clock = new itemBase(modid+"lapisclock");
    public static final Item Dragon_Clock = new itemBase(modid+"dragonclock");
    public static final Item Redstone_Clock = new itemBase(modid+"redstoneclock");
    public static final Item Gold_Clock = new itemBase(modid+"goldclock");
    public static final Item Comp_Torch = new itemBase(modid+"compressedtorch");
    public static final Item Binding_Element = new itemBase(modid+"bindingelement");
    public static final Item Binding_Element2 = new itemBase(modid+"bindingelement2");
    public static final Item Binding_Element3 = new itemBase(modid+"bindingelement3");
    public static final Item time_stick = new itemBase(modid+"time_stick");
    public static final Item time_casing = new itemBase(modid+"time_casing");
    public static final Item time_core = new itemBase(modid+"time_core");
    public static final Item time_particle = new itemBase(modid+"time_particle");
    public static final List<Block> BLOCKS = new ArrayList<>();
    public static final Block Torch_lvl_1 = new BlockTorcherino(modid+"torch_lvl1", TorcherinoEnumLevel.lvl_1);
    public static final Block Torch_lvl_2 = new BlockTorcherino(modid+"torch_lvl2",TorcherinoEnumLevel.lvl_2);
    public static final Block Torch_lvl_3 = new BlockTorcherino(modid+"torch_lvl3",TorcherinoEnumLevel.lvl_3);
    public static final Block Torch_lvl_4 = new BlockTorcherino(modid+"torch_lvl4",TorcherinoEnumLevel.lvl_4);
    public static final Block Torch_lvl_5 = new BlockTorcherino(modid+"torch_lvl5",TorcherinoEnumLevel.lvl_5);
    public static final Block Compressed_Torch_lvl1 = new BlockTorcherino(modid+"compressed_torch_lvl1",TorcherinoEnumLevel.c_lvl_1);
    public static final Block Compressed_Torch_lvl2 = new BlockTorcherino(modid+"compressed_torch_lvl2",TorcherinoEnumLevel.c_lvl_2);
    public static final Block Compressed_Torch_lvl3 = new BlockTorcherino(modid+"compressed_torch_lvl3",TorcherinoEnumLevel.c_lvl_3);
    public static final Block Compressed_Torch_lvl4 = new BlockTorcherino(modid+"compressed_torch_lvl4",TorcherinoEnumLevel.c_lvl_4);
    public static final Block Compressed_Torch_lvl5 = new BlockTorcherino(modid+"compressed_torch_lvl5",TorcherinoEnumLevel.c_lvl_5);
    public static final Block D_Compressed_Torch_lvl1 = new BlockTorcherino(modid+"d_compressed_torch_lvl1",TorcherinoEnumLevel.d_lvl_1);
    public static final Block D_Compressed_Torch_lvl2 = new BlockTorcherino(modid+"d_compressed_torch_lvl2",TorcherinoEnumLevel.d_lvl_2);
    public static final Block D_Compressed_Torch_lvl3 = new BlockTorcherino(modid+"d_compressed_torch_lvl3",TorcherinoEnumLevel.d_lvl_3);
    public static final Block D_Compressed_Torch_lvl4 = new BlockTorcherino(modid+"d_compressed_torch_lvl4",TorcherinoEnumLevel.d_lvl_4);
    public static final Block D_Compressed_Torch_lvl5 = new BlockTorcherino(modid+"d_compressed_torch_lvl5",TorcherinoEnumLevel.d_lvl_5);
    public static final Block Time_Acceleration = new BlockAcceleration(modid+"time_acceleration");
    public static final Block Time_Storage = new BlockTimeStorage(modid+"time_storage");
    public static final Block Time_collectors = new BlockCollectors(modid+"time_collectors");
    public static final Block Particle_collectors_lvl1 = new BlockParticleCollector(modid+"particle_collector_lvl1", ParticleCollectorEnumLevel.lvl_1);
    public static final Block Particle_collectors_lvl2 = new BlockParticleCollector(modid+"particle_collector_lvl2",ParticleCollectorEnumLevel.lvl_2);
    public static final Block Particle_collectors_lvl3 = new BlockParticleCollector(modid+"particle_collector_lvl3",ParticleCollectorEnumLevel.lvl_3);
    public static final Block Time_Manipulator = new BlockTimeManipulator(modid+"time_manipulator");
}